# services: 
#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"

services:
  qdrant:
    image: qdrant/qdrant:latest          # official image
    ports:
      - "6333:6333"                      # host → container
    volumes:
      - qdrant_data:/qdrant/storage      # keep vectors after restarts

  backend:
    build:
      context: .                         # uses the Dockerfile you just fixed
    ports:
      - "8000:8000"                      # host → container
    # environment:
    #   QDRANT_URL: https://ae88571d-4265-4a4d-b3c8-4ebd97fa1f36.europe-west3-0.gcp.cloud.qdrant.io:6333
    #   QDRANT_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.hSE-DMHbdwRqQwKhAoZY2aN43WtWOnn1tO6109wGmR0             # if you need a key, set here
    depends_on:
      - qdrant                           # start DB first

volumes:
  qdrant_data:                           # named volume definition